binance_django/binance_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('main/', include('main.urls')),
    path('admin/', admin.site.urls),
]

binance_django/main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    # path('', views.index, name='index'),
    # These are more like binance python api enpoints
#    path('get_account', views.get_account, name='get_account'),
#    path('accounts', views.get_account, name='accounts'),
#    path('get_asset_balance/<str:asset>', views.get_access_balance, name='get_asset_balance'),
#    # '<int:question_id>/vote/',
#    # These are rest like enpoints
#    path('balances', views.get_account, name='balances'),
#    path('balances/<str:asset>', views.get_access_balance, name='get_asset_balance'),
#    path('save_account', views.save_account, name='save_account'),

    # generic views
#    path('get_accounts', views.IndexView.as_view(), name='get_accounts'),
#    path('get_accounts/<int:pk>/', views.DetailView.as_view(), name='get_accounts_detail'),

    # print(pformat(client.get_all_orders(symbol=TradePairs.ETHBUSD)))
    # path('get_all_orders/<str:tradepair>/', views.get_all_orders_tradepair, name='get_all_orders_tradepair'),

    # path('orders/', views.IndexView.as_view(), name='createorder_list'),
    # path('orders/<int:pk>/', views.DetailView.as_view(), name='createorder_detail'),
    # path('orders/create_order/', views.create_order, name='createorder'),
    path('api/', views.api, name='api'),
    path('api/create_order', views.create_order, name='create_order'),
    path('api/get_all_orders/<str:symbol>', views.get_all_orders, name='get_all_orders'),
    path('api/get_open_orders/<str:symbol>', views.get_open_orders, name='get_open_orders'),
    path('api/get_account', views.get_account, name='get_account'),
    path('api/cancel_order/<str:symbol>/<str:order_id>', views.cancel_order, name='cancel_order')
]

binance_django/main/models.py
import typing
from django.db import models
from pprint import pformat


class GetAccount(models.Model):
    data = models.JSONField(null=True)

    def __str__(self):
        return "get_account %i" % self.pk

    def pformat_data(self):
        return pformat(self.data)


class Account(models.Model):
    makerCommission = models.FloatField()
    takerCommission = models.FloatField()
    buyerCommission = models.FloatField()
    sellerCommission = models.FloatField()
    canTrade = models.BooleanField()
    canWithdraw = models.BooleanField()
    canDeposit = models.BooleanField()
    updateTime = models.PositiveBigIntegerField()
    accountType = models.CharField(max_length=20, )

    def __str__(self):
        return "%s" % self.__dict__

    def factory(dictionary):
        rv, created = Account.objects.get_or_create(
            makerCommission=dictionary['makerCommission'],
            takerCommission=dictionary['takerCommission'],
            buyerCommission=dictionary['buyerCommission'],
            sellerCommission=dictionary['sellerCommission'],
            canTrade=dictionary['canTrade'],
            canWithdraw=dictionary['canWithdraw'],
            canDeposit=dictionary['canDeposit'],
            updateTime=dictionary['updateTime'],
            accountType=dictionary['accountType'], )

        if 'balances' in dictionary:
            for balance in dictionary['balances']:
                rv.balances.get_or_create(
                    asset=balance['asset'],
                    free=balance['free'],
                    locked=balance['locked'], )
        if 'permissions' in dictionary:
            for permission in dictionary['permissions']:
                rv.permissions.get_or_create(permission=permission)
        return rv

    factory = staticmethod(factory)


class Balance(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='balances')
    asset = models.CharField(max_length=10)
    free = models.FloatField()
    locked = models.FloatField()


class Permission(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='permissions')
    permission = models.CharField(max_length=20)


class CreateOrder(models.Model):
    """
    See also https://python-binance.readthedocs.io/en/latest/account.html#id2

    Get data for:
    order = client.create_order(
    symbol='BNBBTC',
    side=SIDE_BUY,
    type=ORDER_TYPE_LIMIT,
    timeInForce=TIME_IN_FORCE_GTC,
    quantity=100,
    price='0.00001')

    """
    symbol = models.CharField(max_length=6)
    # See https://docs.djangoproject.com/en/3.1/topics/db/models/
    side = models.TextChoices('Side', 'BUY')
    type = models.TextChoices('Type', 'LIMIT')
    timeInForce = models.TextChoices('timeInForce', 'GTC')
    quantity = models.FloatField()
    price = models.FloatField()

binance_django/main/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from pprint import pformat
from .binance_helpers import BinanceClient, TradePairs
from django.template import loader
from .models import Balance, Account, GetAccount, CreateOrder
from ast import literal_eval
from django.views import generic
from binance.exceptions import BinanceAPIException, BinanceOrderException
from django.contrib import messages
from django.contrib import messages

def index(request):
    template = loader.get_template('main/index.html')
    context = {}
    return HttpResponse(template.render(context, request))


# def get_account(request):
#     client = BinanceClient().client
#
#     template = loader.get_template('main/get_account.html')
#     account = client.get_account()
#
# #    last = Account.objects.last()
# #    if last is not None and last.updateTime != account.updateTime:
# #        new_account = Account(
# #            makerCommission=account['makerCommission'],
# #            takerCommission=account['takerCommission'],
# #            buyerCommission=account['buyerCommission'],
# #            sellerCommission=account['sellerCommission'],
# #            canTrade=account['canTrade'],
# #            canWithdraw=account['canWithdraw'],
# #            canDeposit=account['canDeposit'],
# #            updateTime=account['updateTime'])
# #        for balance in account.balances:
#
#     context = {'json_response': str(account), 'account': account}
#     return HttpResponse(template.render(context, request))
#
#
# def get_access_balance(request, asset):
#     client = BinanceClient().client
#
#     template = loader.get_template('main/get_asset_balance.html')
#     response = client.get_asset_balance(asset=asset)
#     print(response)
#     context = {'json_response': pformat(response), 'response': response}
#     return HttpResponse(template.render(context, request))
#
#
# def save_account(request):
#     print("save_account")
#     account = request.POST['account']
#
#
#     print(account)
#     print(type(account))
#
#     #    account_info = pickle.loads(account_info)
#     account = literal_eval(account)
#     print(account)
#     print(type(account))
#
#     # Also save as json to experiment with json later.
#     GetAccount.objects.create(data=account)
#
#
#     account_model = Account.factory(account)
#     print(account_model)
#     print(account_model.makerCommission)
#
#     print("Saving account")
#     account_model.save()
#     print("Saved")
#     return HttpResponseRedirect(reverse('main:get_account'))


class IndexView(generic.ListView):
    def get_queryset(self):
        """ return all saved get_account calls"""
        return GetAccount.objects.all()


class DetailView(generic.DetailView):
    model = GetAccount


def get_all_orders_tradepair(request, tradepair):
    template = loader.get_template('main/get_all_orders_tradepair.html')
    client = BinanceClient().client
    orders = client.get_all_orders(symbol=tradepair)
    context = {'orders': orders}
    return HttpResponse(template.render(context, request))


class IndexView(generic.ListView):
    def get_queryset(self):
        return CreateOrder.objects.all()


class DetailView(generic.DetailView):
    model = CreateOrder


def create_order(request):
    print('create order')
    template = loader.get_template('main/create_order.html')
    context = {}
    order_reference = None
    if request.method == 'POST':
        context['error_message'] = 'no errors'
        # Your code for POST
        typea = request.POST['typea']
        symbol = request.POST['symbol']
        side = request.POST['side']
        time_in_force = request.POST['timeInForce']
        quantity = request.POST['quantity']
        price = request.POST['price']

        try:
            order_reference = BinanceClient().client.create_order(
                symbol=symbol,
                side=side,
                type=typea,
                timeInForce=time_in_force,
                quantity=quantity,
                price=price)
            context['message'] = 'Created order %s. Create another ?' % order_reference
        except BinanceAPIException as e:
            # error handling goes here
            context['error_message'] = e.message
            print(e)
        except BinanceOrderException as e:
            context['error_message'] = e.message
            # error handling goes here
            print(e)

    else:
        context['message'] = 'Create an order'
        context['error_message'] = 'no errors'
    return HttpResponse(template.render(context, request))


def get_account(request):
    client = BinanceClient().client

    template = loader.get_template('main/get_account.html')
    account = client.get_account()

    context = {'json_response': pformat(account), 'account': account}
    return HttpResponse(template.render(context, request))


def api(request):
    template = loader.get_template('main/api.html')
    return HttpResponse(template.render({}, request))


def get_all_orders(request, symbol):
    context = {}
    try:
        orders = BinanceClient().client.get_all_orders(symbol=symbol, limit=10)
        context['dict_response'] = orders
    except BinanceAPIException as e:
        messages.error(request, e.message)
        print(e)
    except BinanceOrderException as e:
        messages.error(request, e.message)
        print(e)

    template = loader.get_template('main/order_list.html')
    return HttpResponse(template.render(context, request))


def get_open_orders(request, symbol):
    context = {}
    try:
        orders = BinanceClient().client.get_open_orders(symbol=symbol)
        context['dict_response'] = orders
    except BinanceAPIException as e:
        messages.error(request, e.message)
        print(e)
    except BinanceOrderException as e:
        messages.error(request, e.message)
        print(e)

    template = loader.get_template('main/order_list.html')
    return HttpResponse(template.render(context, request))


def cancel_order(request, symbol, order_id):
    print("cancel_order")
    context = {}
    try:
        dict_response = BinanceClient().client.cancel_order(symbol=symbol, orderId=order_id)
        print('asked api')
        context['dict_response'] = dict_response
    except BinanceAPIException as e:
        # error handling goes here
        messages.error(request, e.message)
        print(e)
    except BinanceOrderException as e:
        messages.error(request, e.message)
        # error handling goes here
        print(e)

    return HttpResponseRedirect(reverse('main:get_all_orders', args=[symbol]))

binance_django/main/templates/main/api.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>api</title>
</head>
<body>
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">

<li><a href="{% url 'main:create_order'    %}">create_order</a></li>
<li><a href="{% url 'main:get_account'     %}">get_account</a></li>
<li><a href="{% url 'main:get_all_orders' 'ETHBUSD' %}">get_all_orders (ETHBUSD)</a></li>
<li><a href="{% url 'main:get_open_orders' 'ETHBUSD' %}">get_open_orders (ETHBUSD)</a></li>

</body>
</html>

binance_django/main/templates/main/create_order.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>create_order</title>
</head>
<body>
{% include './include/header.html' %}
{% load static %}

<h1>Create order</h1>
<p>{{message}}</p>
<p>{{error_message}}</p>

<form action="{% url 'main:create_order' %}" method="post">
    {% csrf_token %}
    <label for="symbol">symbol:</label><br>
    <input type="text" id="symbol" name="symbol" value="ETHBUSD"><br>

    <label for="side">side:</label><br>
    <input type="text" id="side" name="side" value="BUY"><br>

    <label for="typea">type:</label><br>
    <input type="text" id="typea" name="typea" value="LIMIT"><br>

    <label for="timeInForce">timeInForce:</label><br>
    <input type="text" id="timeInForce" name="timeInForce" value="GTC"><br>

    <label for="quantity">quantity:</label><br>
    <input type="text" id="quantity" name="quantity" value="0.1"><br>

    <label for="price">price:</label><br>
    <input type="text" id="price" name="price"><br>

    <input type="submit" value="Create order">
</form>

</body>
</html>

binance_django/main/templates/main/get_account.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>get_account</title>
    <style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td {
  padding: 5px;
  text-align: left;
}

    </style>
</head>
<body>
{% include './include/header.html' %}

<table style="width:100%">
    <caption>get_account</caption>
    <tr>
        <th>asset</th>
        <th>free</th>
        <th>locked</th>
    </tr>
    {% for balance in account.balances %}
    <tr>
        <td>{{ balance.asset }}</td>
        <td>{{ balance.free }}</td>
        <td>{{ balance.locked }}</td>
    </tr>
    {% endfor %}
</table>



{% if json_response %}
<pre>
JSON RESPONSE:

    {{ json_response }}
</pre>
{% else %}
<p>No json_response is available.</p>
{% endif %}

</body>
</html>

binance_django/main/templates/main/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>My test page</title>
</head>
<body>
{% include './include/header.html' %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">

<li><a href="{% url 'main:get_accounts'  %}">get_account</a></li>
<li><a href="{% url 'main:get_all_orders_tradepair' 'ETHBUSD' %}">get_all_orders ETH_BUSD</a></li>

{% if json_response %}
<pre>
JSON RESPONSE:

    {{ json_response }}
</pre>
{% else %}
<p>No json_response is available.</p>
{% endif %}

</body>
</html>

binance_django/main/templates/main/order_list.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>get_all_orders</title>
    <style>
        table, th, td {
          border: 1px solid black;
          border-collapse: collapse;
        }
        th, td {
          padding: 5px;
          text-align: left;
        }
    </style>
</head>
<body>
{% include './include/header.html' %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{% if message.tags %} class="{{ message.tags }}"{% endif %} : {{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% for order in dict_response %}
<pre>
    {{ order|pprint}}
</pre>
{% if order.status != 'FILLED' and order.status != 'CANCELED' %}
<a href="{% url 'main:cancel_order' symbol=order.symbol order_id=order.orderId %}">Cancel order</a>
{% endif %}
{% empty %}
<li>Sorry, nothing in this list.</li>
{% endfor %}

</body>
</html>